import { SavedList } from './types';

export const DEFAULT_CUISINES = [
  'Italian', 'Japanese', 'Mexican', 'Chinese', 'Thai', 'Indian', 'American', 'Fast Food', 'Healthy', 'Korean', 'Vietnam'
];

export const INITIAL_LISTS: SavedList[] = [
  {
    id: 'default-1',
    name: 'Office Favorites',
    isDefault: true,
    restaurants: [
      { id: 'r1', name: 'Joe\'s Pizza', cuisine: 'Pizza', priceLevel: '$', source: 'manual', rating: 4.5 },
      { id: 'r2', name: 'Sushi Zen', cuisine: 'Japanese', priceLevel: '$$', source: 'manual', rating: 4.8 },
    ]
  }
];

export const TRANSLATIONS = {
  en: {
    appTitle: "LunchSpin",
    pick: "Pick",
    discover: "Discover",
    lists: "Lists",
    stats: "Stats",
    settings: "Settings",
    login: "Profile Setup",
    logout: "Switch Profile",
    welcome: "Welcome back,",
    whatToEat: "What to eat?",
    spinBtn: "What Should I Eat?",
    spinning: "Spinning...",
    spinAgain: "Spin Again",
    pickFrom: "Pick from",
    places: "places",
    pleaseCreateList: "Please create a list first!",
    discoverTitle: "Discover New Tastes",
    searchPlaceholder: "e.g. Spicy Ramen nearby...",
    noResults: "No results found. Try a different term!",
    addedToDefault: "Added to your default list!",
    yourCravings: "Your Cravings",
    totalPicks: "Total Picks",
    topCuisine: "Top Cuisine",
    cuisineDist: "Cuisine Distribution",
    recentHistory: "Recent History",
    manageCuisines: "Manage Cuisines",
    addCuisine: "Add Cuisine",
    language: "Language",
    myLists: "My Lists",
    addPlace: "Add Place",
    delete: "Delete",
    cancel: "Cancel",
    add: "Add",
    createList: "Create New List",
    listName: "List Name",
    create: "Create",
    name: "Name",
    email: "Email",
    loginDesc: "Your lists are saved to this browser. Sign in with the same email to access them anytime on this device.",
    loginDisclaimer: "Data is stored locally on this device. No information is sent to external servers.",
    loginBtn: "Access My Lists",
    guestBtn: "Just trying it out? Continue as Guest",
    nearby: "Nearby",
    favorites: "Favorites",
    poweredBy: "Powered by Gemini",
    priceLevel: "Price Level",
    savedToFavorites: "Saved to Favorites!",
    removedFromFavorites: "Removed from Favorites",
    invalidEmail: "Please enter a valid email address.",
    missingFields: "Please fill in all fields.",
    dataManagement: "Data Management",
    exportData: "Export Data (JSON)",
    importData: "Import Data",
    cloudSync: "Cloud Sync",
    comingSoon: "Coming Soon",
    dataExported: "Data copied to clipboard!",
    dataImported: "Data imported successfully!"
  },
  'zh-TW': {
    appTitle: "午餐轉盤",
    pick: "轉盤",
    discover: "探索",
    lists: "清單",
    stats: "統計",
    settings: "設定",
    login: "個人設定",
    logout: "切換使用者",
    welcome: "歡迎回來，",
    whatToEat: "今天吃什麼？",
    spinBtn: "今天吃什麼？",
    spinning: "旋轉中...",
    spinAgain: "再轉一次",
    pickFrom: "從",
    places: "個地點中選擇",
    pleaseCreateList: "請先建立一個清單！",
    discoverTitle: "探索新美味",
    searchPlaceholder: "例如：附近的辣味拉麵...",
    noResults: "找不到結果，試試其他關鍵字！",
    addedToDefault: "已加入預設清單！",
    yourCravings: "你的飲食偏好",
    totalPicks: "總次數",
    topCuisine: "最愛料理",
    cuisineDist: "料理分佈",
    recentHistory: "最近紀錄",
    manageCuisines: "管理料理分類",
    addCuisine: "新增分類",
    language: "語言",
    myLists: "我的清單",
    addPlace: "新增地點",
    delete: "刪除",
    cancel: "取消",
    add: "加入",
    createList: "建立新清單",
    listName: "清單名稱",
    create: "建立",
    name: "名稱",
    email: "電子郵件",
    loginDesc: "您的清單將儲存於此瀏覽器。請使用相同的 Email 登入以存取資料。",
    loginDisclaimer: "資料僅儲存於本裝置，不會上傳至外部伺服器。",
    loginBtn: "存取我的清單",
    guestBtn: "只是試試？以訪客身份繼續",
    nearby: "附近",
    favorites: "最愛",
    poweredBy: "由 Gemini 提供支援",
    priceLevel: "價格等級",
    savedToFavorites: "已儲存至最愛！",
    removedFromFavorites: "已從最愛移除",
    invalidEmail: "請輸入有效的電子郵件地址。",
    missingFields: "請填寫所有欄位。",
    dataManagement: "資料管理",
    exportData: "匯出資料 (JSON)",
    importData: "匯入資料",
    cloudSync: "雲端同步",
    comingSoon: "即將推出",
    dataExported: "資料已複製到剪貼簿！",
    dataImported: "資料匯入成功！"
  }
};